// Creature face drawing. Three modes (spec section 7):
//   A dithered billboard quad in the world, with a wireframe cage
//   B contour line paths drawn like wall segments
//   C portrait panel in the HUD (drawn by hud.ts; this module supplies
//     the image)
// When faces.json holds no entry, a procedural wireframe head built
// from the creature's silhouette key stands in.

import { tuning } from '../config/tuning.ts';
import type { Content, GameState } from '../sim/step.ts';
import type { CreatureInstance } from '../sim/creatures.ts';
import { type Camera, toCameraSpace, projectCameraSpace, scaleAt } from './camera.ts';
import type { SceneInsert } from './wireframe.ts';
import facesRaw from '../data/faces.json';

export type FaceMode = 'A' | 'B' | 'C';

interface FaceEntry {
  img96?: string;
  img48?: string;
  contours?: number[][];
  credit?: string;
}

const faces = facesRaw as Record<string, FaceEntry>;

// Face images generated by the build script, bundled by Vite when present.
const faceUrls: Record<string, string> = {};
const globbed = import.meta.glob('../assets/faces/*.png', { eager: true, query: '?url', import: 'default' });
for (const [path, url] of Object.entries(globbed)) {
  const name = path.split('/').pop()!.replace('.png', '');
  faceUrls[name] = url as string;
}

export function faceCredits(): { creatureId: string; credit: string }[] {
  return Object.entries(faces)
    .filter(([, entry]) => entry.credit)
    .map(([creatureId, entry]) => ({ creatureId, credit: entry.credit! }));
}

// ---------------------------------------------------------------------------
// Procedural placeholder heads, one polyline set per silhouette key.
// Coordinates in a unit square, y down.

type Polyline = [number, number][];

const SILHOUETTES: Record<string, Polyline[]> = {
  arachnid: [
    [[0.35, 0.4], [0.5, 0.3], [0.65, 0.4], [0.65, 0.6], [0.5, 0.7], [0.35, 0.6], [0.35, 0.4]],
    [[0.42, 0.45], [0.45, 0.5]],
    [[0.58, 0.45], [0.55, 0.5]],
    [[0.45, 0.62], [0.47, 0.7]],
    [[0.55, 0.62], [0.53, 0.7]],
    [[0.35, 0.45], [0.1, 0.25]], [[0.35, 0.5], [0.08, 0.5]], [[0.35, 0.55], [0.1, 0.75]],
    [[0.65, 0.45], [0.9, 0.25]], [[0.65, 0.5], [0.92, 0.5]], [[0.65, 0.55], [0.9, 0.75]],
  ],
  rodent: [
    [[0.3, 0.55], [0.5, 0.35], [0.7, 0.55], [0.6, 0.75], [0.4, 0.75], [0.3, 0.55]],
    [[0.35, 0.4], [0.28, 0.2], [0.45, 0.32]],
    [[0.65, 0.4], [0.72, 0.2], [0.55, 0.32]],
    [[0.42, 0.5], [0.44, 0.53]],
    [[0.58, 0.5], [0.56, 0.53]],
    [[0.4, 0.68], [0.15, 0.62]], [[0.4, 0.72], [0.15, 0.72]],
    [[0.6, 0.68], [0.85, 0.62]], [[0.6, 0.72], [0.85, 0.72]],
  ],
  serpent: [
    [[0.3, 0.7], [0.35, 0.45], [0.5, 0.3], [0.65, 0.45], [0.7, 0.7], [0.55, 0.62], [0.45, 0.62], [0.3, 0.7]],
    [[0.42, 0.45], [0.47, 0.48]],
    [[0.58, 0.45], [0.53, 0.48]],
    [[0.5, 0.62], [0.5, 0.78]],
    [[0.5, 0.78], [0.44, 0.85]], [[0.5, 0.78], [0.56, 0.85]],
  ],
  blob: [
    [[0.25, 0.65], [0.3, 0.45], [0.42, 0.35], [0.58, 0.38], [0.7, 0.45], [0.75, 0.6], [0.68, 0.72], [0.5, 0.78], [0.32, 0.74], [0.25, 0.65]],
    [[0.4, 0.5], [0.43, 0.55]],
    [[0.6, 0.52], [0.57, 0.56]],
  ],
  humanoid: [
    [[0.35, 0.3], [0.65, 0.3], [0.68, 0.55], [0.5, 0.72], [0.32, 0.55], [0.35, 0.3]],
    [[0.35, 0.3], [0.4, 0.18], [0.6, 0.18], [0.65, 0.3]],
    [[0.42, 0.42], [0.46, 0.42]],
    [[0.54, 0.42], [0.58, 0.42]],
    [[0.44, 0.6], [0.56, 0.6]],
  ],
  giant: [
    [[0.28, 0.25], [0.72, 0.25], [0.78, 0.6], [0.5, 0.82], [0.22, 0.6], [0.28, 0.25]],
    [[0.38, 0.42], [0.44, 0.42]],
    [[0.56, 0.42], [0.62, 0.42]],
    [[0.4, 0.66], [0.6, 0.66], [0.55, 0.72], [0.45, 0.72], [0.4, 0.66]],
    [[0.3, 0.3], [0.36, 0.36]], [[0.7, 0.3], [0.64, 0.36]],
  ],
  wraith: [
    [[0.35, 0.35], [0.5, 0.25], [0.65, 0.35], [0.65, 0.6], [0.6, 0.75], [0.55, 0.62], [0.5, 0.78], [0.45, 0.62], [0.4, 0.75], [0.35, 0.6], [0.35, 0.35]],
    [[0.43, 0.42], [0.47, 0.45]],
    [[0.57, 0.42], [0.53, 0.45]],
  ],
  stalker: [
    [[0.3, 0.6], [0.4, 0.3], [0.6, 0.3], [0.7, 0.6], [0.5, 0.7], [0.3, 0.6]],
    [[0.4, 0.42], [0.46, 0.46]],
    [[0.6, 0.42], [0.54, 0.46]],
    [[0.44, 0.58], [0.5, 0.62], [0.56, 0.58]],
    [[0.4, 0.3], [0.35, 0.15]], [[0.6, 0.3], [0.65, 0.15]],
  ],
  wizard: [
    [[0.35, 0.45], [0.65, 0.45], [0.6, 0.7], [0.5, 0.78], [0.4, 0.7], [0.35, 0.45]],
    [[0.3, 0.45], [0.7, 0.45], [0.5, 0.1], [0.3, 0.45]],
    [[0.42, 0.52], [0.46, 0.52]],
    [[0.54, 0.52], [0.58, 0.52]],
    [[0.42, 0.68], [0.46, 0.85], [0.54, 0.85], [0.58, 0.68]],
  ],
};

const FALLBACK_SILHOUETTE: Polyline[] = [
  [[0.35, 0.35], [0.65, 0.35], [0.65, 0.65], [0.35, 0.65], [0.35, 0.35]],
  [[0.42, 0.45], [0.46, 0.45]],
  [[0.54, 0.45], [0.58, 0.45]],
  [[0.44, 0.58], [0.56, 0.58]],
];

// ---------------------------------------------------------------------------
// Image cache: per creature, per palette colour, a tinted 1-bit canvas.

const imageCache = new Map<string, HTMLCanvasElement>();
const photoBitmaps = new Map<string, HTMLImageElement | null>();
let placeholdersLogged = false;

function silhouetteLines(content: Content, defId: string): Polyline[] {
  const sil = content.creatures[defId]?.silhouette ?? '';
  return SILHOUETTES[sil] ?? FALLBACK_SILHOUETTE;
}

function loadPhoto(defId: string): HTMLImageElement | null {
  if (photoBitmaps.has(defId)) return photoBitmaps.get(defId)!;
  const entry = faces[defId];
  const key = entry?.img96?.split('/').pop()?.replace('.png', '');
  const url = key ? faceUrls[key] : undefined;
  if (!url) {
    photoBitmaps.set(defId, null);
    return null;
  }
  const img = new Image();
  img.src = url;
  photoBitmaps.set(defId, img);
  return img;
}

/** True when a built photograph exists for the creature. */
export function hasFace(defId: string): boolean {
  const entry = faces[defId];
  const key = entry?.img96?.split('/').pop()?.replace('.png', '');
  return key !== undefined && faceUrls[key] !== undefined;
}

/** Report once which creatures run on placeholders (spec section 7). */
export function logPlaceholders(content: Content): void {
  if (placeholdersLogged) return;
  placeholdersLogged = true;
  const missing = Object.keys(content.creatures).filter((id) => !faces[id]?.img96);
  if (missing.length > 0) {
    console.info(`DAGGORATH.JS: procedural placeholder faces in use for: ${missing.join(', ')}`);
  }
}

/** A tinted face canvas for the creature, photo when built, else placeholder. */
export function faceImage(content: Content, defId: string, fg: string, size: number): HTMLCanvasElement {
  const cacheKey = `${defId}|${fg}|${size}`;
  const hit = imageCache.get(cacheKey);
  if (hit) return hit;
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d')!;
  const photo = loadPhoto(defId);
  if (photo && photo.complete && photo.naturalWidth > 0) {
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(photo, 0, 0, size, size);
    // Tint the 1-bit image to the phosphor colour.
    ctx.globalCompositeOperation = 'source-in';
    ctx.fillStyle = fg;
    ctx.fillRect(0, 0, size, size);
    ctx.globalCompositeOperation = 'source-over';
  } else {
    ctx.strokeStyle = fg;
    ctx.lineWidth = Math.max(1, Math.floor(size / 48));
    for (const line of silhouetteLines(content, defId)) {
      ctx.beginPath();
      line.forEach(([x, y], i) => {
        if (i === 0) ctx.moveTo(x * size, y * size);
        else ctx.lineTo(x * size, y * size);
      });
      ctx.stroke();
    }
    // Do not cache while a photo may still be loading.
    if (photo && !photo.complete) return canvas;
  }
  imageCache.set(cacheKey, canvas);
  return canvas;
}

export function clearFaceCache(): void {
  imageCache.clear();
}

// ---------------------------------------------------------------------------
// World-space drawing

export interface VisibleCreature {
  creature: CreatureInstance;
  depth: number;
}

/** Creatures the player can currently see, with camera depth. */
export function visibleCreatures(
  content: Content,
  state: GameState,
  cam: Camera,
  radius: number,
  visible: Set<number>,
): VisibleCreature[] {
  const level = content.levels[state.player.levelId]!;
  const out: VisibleCreature[] = [];
  for (const c of state.creatures) {
    if (c.levelId !== state.player.levelId || c.hp <= 0) continue;
    // The flood-visibility set already stops at walls and doors, so any
    // creature standing in a visible cell is genuinely in view.
    if (!visible.has(c.y * level.size.w + c.x)) continue;
    const [, , zc] = toCameraSpace(cam, c.x + 0.5, 0.5, c.y + 0.5);
    if (zc < tuning.render.nearClip && !(c.x === state.player.x && c.y === state.player.y)) continue;
    if (Math.hypot(c.x - state.player.x, c.y - state.player.y) > radius + 0.5) continue;
    out.push({ creature: c, depth: Math.max(zc, tuning.render.nearClip) });
  }
  return out;
}

/** Build painter inserts that draw each creature at its depth. */
export function creatureInserts(
  ctx: CanvasRenderingContext2D,
  content: Content,
  state: GameState,
  cam: Camera,
  list: VisibleCreature[],
  mode: FaceMode,
  fg: string,
  radius: number,
  brightest: number,
): SceneInsert[] {
  return list.map(({ creature, depth }) => ({
    depth,
    draw: () => {
      const cx = creature.x + 0.5;
      const cz = creature.y + 0.5;
      const size = tuning.render.creatureSize;
      const [xc, yc, zc] = toCameraSpace(cam, cx, 0.5, cz);
      if (zc < tuning.render.nearClip) return;
      const p = projectCameraSpace(xc, yc, zc);
      const px = Math.round(p.sx);
      const py = Math.round(p.sy);
      const half = Math.max(2, Math.round(scaleAt(size, zc) / 2));
      if (mode === 'B') {
        drawContours(ctx, content, creature.defId, fg, px, py, half);
      } else if (mode === 'A') {
        if (hasFace(creature.defId)) {
          const img = faceImage(content, creature.defId, fg, half * 2 >= 48 ? 96 : 48);
          ctx.imageSmoothingEnabled = false;
          ctx.drawImage(img, px - half, py - half, half * 2, half * 2);
        } else {
          // Placeholders draw as vectors so they stay crisp at any scale.
          drawContours(ctx, content, creature.defId, fg, px, py, half);
        }
        // Wireframe cage keeps the face diegetic.
        ctx.strokeStyle = fg;
        ctx.strokeRect(px - half + 0.5, py - half + 0.5, half * 2 - 1, half * 2 - 1);
      }
      if (mode === 'C') {
        // The world stays photograph-free; a wireframe cage marks the
        // creature and the HUD portrait panel shows the face.
        ctx.strokeStyle = fg;
        ctx.strokeRect(px - half + 0.5, py - half + 0.5, half * 2 - 1, half * 2 - 1);
      }
    },
  }));
}

function drawContours(
  ctx: CanvasRenderingContext2D,
  content: Content,
  defId: string,
  fg: string,
  px: number,
  py: number,
  half: number,
): void {
  const entry = faces[defId];
  const source: Polyline[] =
    entry?.contours && entry.contours.length > 0
      ? entry.contours.map((flat) => {
          const line: Polyline = [];
          for (let i = 0; i + 1 < flat.length; i += 2) line.push([flat[i]!, flat[i + 1]!]);
          return line;
        })
      : silhouetteLines(content, defId);
  ctx.strokeStyle = fg;
  ctx.lineWidth = 1;
  for (const line of source) {
    ctx.beginPath();
    line.forEach(([x, y], i) => {
      const sx = px - half + x * half * 2;
      const sy = py - half + y * half * 2;
      if (i === 0) ctx.moveTo(sx, sy);
      else ctx.lineTo(sx, sy);
    });
    ctx.stroke();
  }
}
